#!/usr/bin/env ruby

require "mk_time"

t = MkTime.new(ARGV[0])
puts "     UTC: #{t.utc.strftime('%Y-%m-%d %H:%M:%S.%3N')}"
puts "     JST: #{t.jst.strftime('%Y-%m-%d %H:%M:%S.%3N')}"
puts "      JD: #{t.jd} day"
puts "       T: #{t.t} century"
puts " UTC-TAI: #{t.utc_tai} sec"
puts "LEAP_SEC: #{t.leap_sec} sec"  # = utc_tai
puts "    DUT1: #{t.dut1} sec"
puts "  deltaT: #{t.dt} sec"
puts "     TAI: #{t.tai.strftime('%Y-%m-%d %H:%M:%S.%3N')}"
puts "     UT1: #{t.ut1.strftime('%Y-%m-%d %H:%M:%S.%3N')}"
puts "      TT: #{t.tt .strftime('%Y-%m-%d %H:%M:%S.%3N')}"
puts "     TCG: #{t.tcg.strftime('%Y-%m-%d %H:%M:%S.%3N')}"
puts "     TCB: #{t.tcb.strftime('%Y-%m-%d %H:%M:%S.%3N')}"
puts "     TDB: #{t.tdb.strftime('%Y-%m-%d %H:%M:%S.%3N')}"

